---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserverwcon-deployment
  labels:
    app: rest-server-wcon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server-wcon
  template:
    metadata:
      labels:
        app: rest-server-wcon
    spec:
      containers:
        - name: rest-server-wcon
          image: cryonicstrider/python-docker:v5.42
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_DATABASE_HOST
              value: 'mysqldb:3306'
            - name: MYSQL_DATABASE_DB
              value: 'pytcheck'
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: fl-api-secrets
                  key: db_root_password

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: rest-server-wcon
