apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: cryonicstrider/flask-react:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend
